context:
  name: easyscience
  version: 1.2.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/easyscience-${{ version }}.tar.gz
  sha256: 6a802d45f6599bb11579f16031663ada82ff54756a1ca78667a64105f22ad739

build:
  number: 0
  skip:
    - match(python, "<3.11")
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - hatchling <=1.21.0
    - setuptools-git-versioning
    - pip
  run:
    - python
    - asteval
    - bumps
    - dfo-ls
    - lmfit
    - numpy <2
    - uncertainties
    - xarray
    - pint ==0.23
    - scipp

tests:
  - script: python -c "import easyscience"
    requirements:
      run:
        - python

about:
  homepage: https://easyscience.github.io/EasyScience/
  summary: Generic logic for easyScience libraries
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MridulS
