context:
  name: easyscience
  version: "1.3.0"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/easyscience-${{ version }}.tar.gz
  sha256: 1160fb26539ecc6647542727857a4c3943ceca8ba911ad5f2b0b5bf176d616f6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling <=1.21.0
    - setuptools-git-versioning
    - pip
  run:
    - python >=${{ python_min }},<3.13
    - asteval
    - bumps
    - dfo-ls
    - lmfit
    - numpy <2
    - uncertainties
    - xarray
    - pint ==0.23
    - scipp

tests:
  - script: python -c "import easyscience"
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  homepage: https://easyscience.github.io/EasyScience/
  summary: Generic logic for easyScience libraries
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MridulS
